Repository Hardhat-Enterprises/Deakin-Detonator-Toolkit, pull requests merged in 2024-08, with the labels that each got.

#724 708 feature request baseline arpaname
  src/components/Arpaname/arpaname.tsx
Labels: Awaiting User Update, Baseline

#725 713 feature request whois
  src-tauri/tauri.conf.json
  src/components/RouteWrapper.tsx
  src/components/Whois/Whois.tsx
Labels: Awaiting User Update

#726 572 bug fix baseline gyoithon
  src/components/Gyoithon/Gyoithon.tsx
Labels: Awaiting User Update, Baseline

#730 576 bug fix baseline cewl
  src/components/Cewl/Cewl.tsx
Labels: Baseline

#736 589 bug baseline ftpconnect
  src/components/FTP/FTPconnect.tsx
  src/components/RouteWrapper.tsx
Labels: Awaiting User Update, Baseline

#710 702 bug baseline arjun
  src/components/Arjuntool/Arjuntool.tsx
Labels: Baseline

#745 622 bug fix baseline CVE 2022 24112
  src/components/CVE-2022-24112/CVE-2022-24112.tsx
Labels: Baseline

#755 746 bug baseline CVE 2022 36804
  src/components/CVE-2022-36804/CVE-2022-36804.tsx
Labels: Awaiting Assignee Update

#770 Enhance UI with advanced features and improvements for NIKTO TOOL
  src/components/Nikto/Nikto.tsx
Labels: Awaiting Assignee Update
