Repository Hardhat-Enterprises/Deakin-Detonator-Toolkit, pull requests merged in 2024-05, with the labels that each got.

#497 Foremost Bug Fix
  src/components/Foremost/Foremost.tsx
Labels: Application Testing

#530 New branch for Netcat improvements and formatted
  src/components/Netcat/Netcat.tsx
  src/components/Netcat/netcatTerminal.sh
Labels: Application Testing

#626 544 feature request whatweb tool
  src-tauri/tauri.conf.json
  src/components/RouteWrapper.tsx
  src/components/WhatWeb/WhatWeb.tsx
Labels: Awaiting User Update

#653 502 feature request netcat listen and connect
  src/components/Netcat/Netcat.tsx
Labels: Application Testing

#656 296 cancel operation ddt wide rollout 3
  src/components/RTsort/RTsort.tsx
Labels: Application Testing

#491 Fix DirbTool Command Options for Case Insensitive, Print Location Header, and HTTP Code Errors
  src/components/DirbTool/DirbTool.tsx
Labels: Awaiting User Update

#654 641 feature request gitleak tool integration
  src-tauri/tauri.conf.json
  src/components/Gitleaks/Gitleaks.tsx
  src/components/RouteWrapper.tsx
Labels: Application Testing

#568 Tooltip Grammatical Error Corrections
  src/components/Urlsnarf/Urlsnarf.tsx
Labels: Awaiting User Update

#631 503 feature request AMAP tool
  src-tauri/tauri.conf.json
  src/components/Amap/Amap.tsx
  src/components/RouteWrapper.tsx
Labels: Application Testing

#535 409 feature request airbase ng
  src/components/AirbaseNG/AirbaseNG.tsx
Labels: Application Testing

#562 Feature request- Bully tool
  src-tauri/tauri.conf.json
  src/components/Bully/Bully.tsx
  src/components/RouteWrapper.tsx
Labels: Application Testing, Awaiting User Update

#666 609 bug fix baseline snmpcheck
  src/components/SnmpCheck/SnmpCheck.tsx
Labels: Awaiting User Update

#676 602 bug fix baseline rtsort
  src/components/RTsort/RTsort.tsx
Labels: Awaiting User Update

#673 587 bug fix baseline ffuf
  src/components/Ffuf/FfufTool.tsx
Labels: Awaiting User Update

#658 651 feature request implement tshark packet sniffer
  src-tauri/tauri.conf.json
  src/components/RouteWrapper.tsx
  src/components/TShark/TShark.tsx
Labels: Awaiting User Update

#655 625 feature request handleprocessdata improvement
  src/utils/CommandHelper.ts
Labels: Application Testing

#649 594 bug fix baseline johntheripper
  src/components/JohnTheRipper/JohnTheRipper.tsx
Labels: Application Testing, Awaiting User Update

#629 511-feature-request-nikto-tool-pull-request
  src-tauri/tauri.conf.json
  src/components/Nikto/Nikto.tsx
  src/components/RouteWrapper.tsx
Labels: Application Testing

#615 CVE-2022-36804 Bitbucket server exploitation.
  src-tauri/exploits/cve-2022-36804.py
  src/components/CVE-2022-36804/CVE-2022-36804.tsx
  src/components/RouteWrapper.tsx
Labels: vulnerabilties, Application Testing, Awaiting User Update

#634 407 feature request fcrackzip tools
  src/components/Fcrackzip/Fcrackzip.tsx
Labels: Awaiting User Update

#681 606 bug fix baseline shodan
  src/components/Shodan/Shodan-API-Tool.tsx
Labels: Awaiting User Update

#624 506 feature request arpaname tool
  src-tauri/tauri.conf.json
  src/components/Arpaname/arpaname.tsx
  src/components/RouteWrapper.tsx
Labels: Awaiting User Update

#674 612 bug fix baseline urlsnarf
  src/components/Urlsnarf/Urlsnarf.tsx
Labels: Awaiting User Update

#698 610 baseline the harvester revision
  .yarn/install-state.gz
  .yarnrc.yml
  src/components/theharvester/theharvester.tsx
Labels: Awaiting User Update

#687 baselinefix arpspoof
  src/components/ArpSpoof/ArpSpoof.tsx
Labels: Awaiting User Update
