Repository Hardhat-Enterprises/Deakin-Detonator-Toolkit, pull requests merged in 2024-09, with the labels that each got.

#742 597 Baseline Nbtscan
  src/components/NbtscanTool/NbtscanTool.tsx
Labels: Awaiting Assignee Update

#845 705-bug-libegl-warning-egl-failed-to-create-dri2-screen
  libgl-bug-fix.md
Labels: On hold

#741 Changes in SaveOutputToTextFile - enhancement
  src/components/SaveOutputToFile/SaveOutputToTextFile.tsx
Labels: Awaiting Assignee Update

#836 File uploader
  install-update-media/dependencies.json
  package.json
  src-tauri/src/file_handler.rs
  src-tauri/src/main.rs
  src/components/FileHandler/FileHandler.tsx
  src/components/FileHandler/FilePicker.tsx
  src/components/Rainbowcrack/Rainbowcrack.tsx
  yarn.lock
Labels: Application Testing

#818 791 feature request unicornscan tool implementation
  src-tauri/tauri.conf.json
  src/components/RouteWrapper.tsx
  src/components/Unicornscan/Unicornscan.tsx
Labels: Awaiting Assignee Update

#844 Baselining Enum4Linux
  src/components/Enum4Linux/Enum4Linux.tsx
Labels: Awaiting Assignee Update

#864 Fixed Installation Modal Pop-Up Issue
  src-tauri/tauri.conf.json
Labels: Awaiting Assignee Update

#783 Baseline Netcat #598
  src/components/Netcat/Netcat.tsx
Labels: Awaiting Assignee Update

#870 804 feature request sqlninja tool implementation
  src-tauri/tauri.conf.json
  src/components/RouteWrapper.tsx
  src/components/Sqlninja/sqlninja.tsx
Labels: Awaiting Assignee Update

#911 [Feature Request]: Aircrack-NG adding/editing features #856
  src/components/AircrackNG/AircrackNG.tsx
Labels: Awaiting Assignee Update

#841 509 feature request cloudbrute tool
  src-tauri/tauri.conf.json
  src/components/CloudBrute/CloudBrute.tsx
  src/components/RouteWrapper.tsx
Labels: Awaiting Assignee Update
